overrides:
  glob: 12.0.0
  js-cookie: 3.0.7
  ws: 8.20.1
  vite: 'catalog:'
  vitest: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.333e612a4d9d966e79724c336ba7bf422f79b442
  vitest: 4.1.9
  vite-plus: 0.0.0-commit.333e612a4d9d966e79724c336ba7bf422f79b442
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
