overrides:
  glob: 12.0.0
  js-cookie: 3.0.7
  ws: 8.20.1
  '@voidzero-dev/vite-plus-core': https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1703
  '@voidzero-dev/vite-plus-test': https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1703
  '@voidzero-dev/vite-plus-prompts': https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-prompts@1703
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/vite-plus-core'
  - '@voidzero-dev/vite-plus-test'
  - '@voidzero-dev/vite-plus-prompts'
